# Generated by Django 4.2.23 on 2025-08-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="interest",
            field=models.CharField(
                choices=[
                    ("after_school", "After-School Enrichment"),
                    ("small_group", "Small Group Tutoring"),
                    ("assessments", "Educational Assessments"),
                    ("programs", "Signature Programs"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
