# Generated by Django 4.2.23 on 2025-08-30 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0023_populate_date_range_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(help_text="Note content")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this note is visible to the parent",
                    ),
                ),
                (
                    "visibility_scope",
                    models.CharField(
                        choices=[
                            ("private_staff", "Private to staff"),
                            ("public_parent", "Visible to parent"),
                        ],
                        default="private_staff",
                        help_text="Who can see this note",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "soft_deleted",
                    models.BooleanField(
                        default=False, help_text="Soft delete for audit trail"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_notes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edited_by_last",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_notes_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="programs.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-created_at"],
                        name="notes_stude_student_cfe52d_idx",
                    ),
                    models.Index(
                        fields=["is_public", "student"],
                        name="notes_stude_is_publ_3473d8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ParentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(help_text="Note content")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this note is visible to the parent",
                    ),
                ),
                (
                    "visibility_scope",
                    models.CharField(
                        choices=[
                            ("private_staff", "Private to staff"),
                            ("public_parent", "Visible to parent"),
                        ],
                        default="private_staff",
                        help_text="Who can see this note",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "soft_deleted",
                    models.BooleanField(
                        default=False, help_text="Soft delete for audit trail"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_notes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edited_by_last",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_notes_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["parent", "-created_at"],
                        name="notes_paren_parent__6097a3_idx",
                    ),
                    models.Index(
                        fields=["is_public", "parent"],
                        name="notes_paren_is_publ_24b1ba_idx",
                    ),
                ],
            },
        ),
    ]
