# Generated by Django 4.2.24 on 2025-10-21 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpersonationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the impersonation session started",
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the impersonation session ended",
                        null=True,
                    ),
                ),
                (
                    "readonly",
                    models.BooleanField(
                        default=True,
                        help_text="Whether write operations were blocked during this session",
                    ),
                ),
                (
                    "reason_note",
                    models.TextField(
                        blank=True, help_text="Optional reason for impersonation"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the admin when starting impersonation",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent string"),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        help_text="The admin/staff user who initiated the impersonation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_sessions_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        help_text="The user being impersonated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_sessions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="audit_imper_started_66272a_idx"
                    ),
                    models.Index(
                        fields=["admin_user", "-started_at"],
                        name="audit_imper_admin_u_353000_idx",
                    ),
                    models.Index(
                        fields=["target_user", "-started_at"],
                        name="audit_imper_target__68a3ab_idx",
                    ),
                ],
            },
        ),
    ]
