# Generated by Django 4.2.24 on 2025-09-07 02:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NDASignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signature_data",
                    models.TextField(help_text="Base64 encoded signature image data"),
                ),
                (
                    "signed_name",
                    models.CharField(
                        help_text="Name as signed by the contractor", max_length=255
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the NDA was signed",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="IP address of the signer"),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string from the browser"
                    ),
                ),
                (
                    "contractor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nda_signature",
                        to="people.contractor",
                    ),
                ),
            ],
            options={
                "verbose_name": "NDA Signature",
                "verbose_name_plural": "NDA Signatures",
            },
        ),
    ]
