# Generated by Django 4.2.24 on 2025-09-07 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0002_ndasignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="nda_approved",
            field=models.BooleanField(
                default=False, help_text="Admin approval for NDA signature"
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="nda_approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When the NDA was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="nda_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who approved the NDA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_ndas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="w9_approved",
            field=models.BooleanField(
                default=False, help_text="Admin approval for W-9 document"
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="w9_approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When the W-9 was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="w9_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who approved the W-9",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_w9s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
