# Generated by Django 4.2.23 on 2025-08-04 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramBuildout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("expected_students", models.PositiveIntegerField()),
                ("num_days", models.PositiveIntegerField()),
                ("sessions_per_day", models.PositiveIntegerField(default=1)),
                (
                    "total_expected_revenue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "program_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildouts",
                        to="programs.programtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "default_percent_of_revenue",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("responsibilities", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProgramRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent_of_revenue",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "hour_frequency",
                    models.CharField(
                        choices=[
                            ("PER_PROGRAM", "Per Program"),
                            ("PER_SESSION", "Per Session"),
                            ("PER_KID", "Per Kid"),
                            ("PER_SESSION_PER_KID", "Per Session per Kid"),
                            ("ADMIN_FLAT", "Admin Flat"),
                            ("OVERRIDE", "Manual Override"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "hour_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base number for frequency (e.g. 0.5 per session)",
                        max_digits=6,
                    ),
                ),
                (
                    "override_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "buildout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="programs.programbuildout",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="programs.role"
                    ),
                ),
            ],
            options={
                "unique_together": {("buildout", "role")},
            },
        ),
    ]
