# Generated by Django 4.2.23 on 2025-08-04 21:41

from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal


def migrate_roles_to_hourly_rates(apps, schema_editor):
    """Migrate existing roles to use hourly rates instead of percentages."""
    Role = apps.get_model('programs', 'Role')
    
    # Set default hourly rates based on previous percentages
    # These are rough estimates - adjust as needed
    rate_mapping = {
        'Facilitator': 25.00,
        'Curriculum Designer': 35.00,
        'Admin Support': 20.00,
        'Owner Oversight': 40.00,
        'Float Support': 18.00,
    }
    
    for role in Role.objects.all():
        if role.name in rate_mapping:
            role.hourly_rate = rate_mapping[role.name]
        else:
            role.hourly_rate = 25.00  # Default rate
        role.save()


def create_base_costs(apps, schema_editor):
    """Create initial base costs."""
    BaseCost = apps.get_model('programs', 'BaseCost')
    
    base_costs = [
        {
            'name': 'Materials & Supplies',
            'cost_per_student': 15.00,
            'description': 'Covers materials like printed handouts, manipulatives, STEM kits, art supplies.'
        },
        {
            'name': 'Location',
            'cost_per_student': 25.00,
            'description': 'Site rental or partner facility share for in-person delivery.'
        },
        {
            'name': 'Platform & Insurance',
            'cost_per_student': 10.00,
            'description': 'Business infrastructure, web platform, liability coverage.'
        },
    ]
    
    for cost_data in base_costs:
        BaseCost.objects.get_or_create(
            name=cost_data['name'],
            defaults=cost_data
        )


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_programbuildout_role_programrole"),
    ]

    operations = [
        # Add new fields to ProgramType
        migrations.AddField(
            model_name='programtype',
            name='rate_per_student',
            field=models.DecimalField(
                max_digits=8,
                decimal_places=2,
                default=Decimal('100.00'),
                help_text='Base rate charged per student'
            ),
        ),
        
        # Add new fields to Role
        migrations.AddField(
            model_name='role',
            name='hourly_rate',
            field=models.DecimalField(
                max_digits=8,
                decimal_places=2,
                default=Decimal('25.00'),
                help_text='Hourly rate for this role'
            ),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        
        # Create BaseCost model
        migrations.CreateModel(
            name='BaseCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_per_student', models.DecimalField(
                    max_digits=8,
                    decimal_places=2,
                    help_text='Cost per student for this base cost'
                )),
                ('description', models.TextField()),
            ],
        ),
        
        # Create ProgramBaseCost model
        migrations.CreateModel(
            name='ProgramBaseCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(
                    max_digits=6,
                    decimal_places=2,
                    default=Decimal('1.00'),
                    help_text='Multiplier for the base cost (e.g., 1.5 for higher cost programs)'
                )),
                ('base_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.basecost')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_costs', to='programs.programtype')),
            ],
            options={
                'unique_together': {('program_type', 'base_cost')},
            },
        ),
        
        # Remove total_expected_revenue from ProgramBuildout
        migrations.RemoveField(
            model_name='programbuildout',
            name='total_expected_revenue',
        ),
        
        # Add buildout field to ProgramInstance
        migrations.AddField(
            model_name='programinstance',
            name='buildout',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='programs.programbuildout',
                help_text='Optional buildout template to use for this instance'
            ),
        ),
        
        # Run data migrations
        migrations.RunPython(migrate_roles_to_hourly_rates),
        migrations.RunPython(create_base_costs),
    ]
