# Generated by Django 4.2.23 on 2025-08-04 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0003_auto_20250804_2141"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="programrole",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="role",
            name="default_percent_of_revenue",
        ),
        migrations.AddField(
            model_name="programrole",
            name="program_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="programs.programtype",
            ),
        ),
        migrations.AlterField(
            model_name="programrole",
            name="override_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Manual override for total hours (ignores frequency calculation)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="programtype",
            name="rate_per_student",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base rate charged per student",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2, help_text="Hourly rate for this role", max_digits=8
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programrole",
            unique_together={("program_type", "role")},
        ),
        migrations.RemoveField(
            model_name="programrole",
            name="buildout",
        ),
        migrations.RemoveField(
            model_name="programrole",
            name="percent_of_revenue",
        ),
    ]
