# Generated by Django 4.2.23 on 2025-08-04 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0004_alter_programrole_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programrole",
            name="program_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="programs.programtype",
            ),
        ),
    ]
