# Generated by Django 4.2.23 on 2025-08-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0006_auto_20250806_2147"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programbuildout",
            options={"ordering": ["title"]},
        ),
        migrations.RemoveField(
            model_name="programinstance",
            name="program_type",
        ),
        migrations.AlterField(
            model_name="basecost",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="basecost",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("PER_WORKSHOP_CONCEPT", "Per Workshop Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_WORKSHOP", "Per Workshop"),
                    ("PER_SESSION", "Per Session"),
                    ("PER_STUDENT", "Per Student"),
                    ("PER_YEAR", "Per Year"),
                    ("ADMIN_FLAT", "Admin Flat"),
                    ("OVERRIDE", "Manual Override"),
                ],
                help_text="How often this cost occurs",
                max_length=32,
            ),
        ),
    ]
