# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_programbuildout_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programbuildout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='programbuildout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
