# Generated by Django 4.2.23 on 2025-08-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0007_alter_programbuildout_options_and_more"),
    ]

    operations = []
