# Generated by Django 4.2.23 on 2025-08-07 00:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0010_merge_20250806_2234"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildoutBaseCostAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for the base cost",
                        max_digits=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BuildoutResponsibilityAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Responsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Responsibility name/title", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("PER_WORKSHOP_CONCEPT", "Per Workshop Concept"),
                            ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                            ("PER_WORKSHOP", "Per Workshop"),
                            ("PER_SESSION", "Per Session"),
                        ],
                        help_text="How often this responsibility occurs",
                        max_length=32,
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hours per frequency unit",
                        max_digits=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["role__title", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="buildoutresponsibility",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="buildoutresponsibility",
            name="buildout",
        ),
        migrations.RemoveField(
            model_name="buildoutresponsibility",
            name="role",
        ),
        migrations.AlterModelOptions(
            name="basecost",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="programbuildout",
            options={"ordering": ["title", "-version_number"]},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["title"]},
        ),
        migrations.RenameField(
            model_name="basecost",
            old_name="amount",
            new_name="rate",
        ),
        migrations.RenameField(
            model_name="role",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="buildoutroleassignment",
            name="percent_of_revenue",
        ),
        migrations.RemoveField(
            model_name="instanceroleassignment",
            name="override_revenue_share",
        ),
        migrations.RemoveField(
            model_name="programtype",
            name="default_new_workshop_concepts_per_year",
        ),
        migrations.RemoveField(
            model_name="programtype",
            name="default_num_facilitators",
        ),
        migrations.RemoveField(
            model_name="programtype",
            name="default_num_new_facilitators",
        ),
        migrations.RemoveField(
            model_name="programtype",
            name="default_registration_form",
        ),
        migrations.RemoveField(
            model_name="programtype",
            name="default_sessions_per_workshop",
        ),
        migrations.RemoveField(
            model_name="programtype",
            name="default_students_per_workshop",
        ),
        migrations.RemoveField(
            model_name="programtype",
            name="default_workshops_per_facilitator_per_year",
        ),
        migrations.RemoveField(
            model_name="programtype",
            name="rate_per_student",
        ),
        migrations.RemoveField(
            model_name="programtype",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="programtype",
            name="target_grade_levels",
        ),
        migrations.RemoveField(
            model_name="role",
            name="hourly_rate",
        ),
        migrations.AddField(
            model_name="basecost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="basecost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="buildoutroleassignment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instanceroleassignment",
            name="override_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override hourly rate for this assignment",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="default_forms",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_buildouts",
                to="programs.registrationform",
            ),
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="is_new_workshop",
            field=models.BooleanField(
                default=False, help_text="Whether this is a new workshop concept"
            ),
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="rate_per_student",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Rate charged per student",
                max_digits=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="roles",
            field=models.ManyToManyField(
                related_name="buildouts",
                through="programs.BuildoutRoleAssignment",
                to="programs.role",
            ),
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="version_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="default_responsibilities",
            field=models.TextField(
                blank=True,
                help_text="Default responsibilities used as templates when included in a buildout",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="basecost",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("PER_WORKSHOP_CONCEPT", "Per Workshop Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_WORKSHOP", "Per Workshop"),
                    ("PER_SESSION", "Per Session"),
                ],
                help_text="How often this cost occurs",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name="programbuildout",
            unique_together={("program_type", "title", "version_number")},
        ),
        migrations.DeleteModel(
            name="BuildoutBaseCost",
        ),
        migrations.DeleteModel(
            name="BuildoutResponsibility",
        ),
        migrations.AddField(
            model_name="responsibility",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsibilities",
                to="programs.role",
            ),
        ),
        migrations.AddField(
            model_name="buildoutresponsibilityassignment",
            name="buildout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsibility_assignments",
                to="programs.programbuildout",
            ),
        ),
        migrations.AddField(
            model_name="buildoutresponsibilityassignment",
            name="responsibility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="programs.responsibility",
            ),
        ),
        migrations.AddField(
            model_name="buildoutbasecostassignment",
            name="base_cost",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="programs.basecost"
            ),
        ),
        migrations.AddField(
            model_name="buildoutbasecostassignment",
            name="buildout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_cost_assignments",
                to="programs.programbuildout",
            ),
        ),
        migrations.RemoveField(
            model_name="programbuildout",
            name="new_workshop_concepts_per_year",
        ),
        migrations.RemoveField(
            model_name="programbuildout",
            name="workshops_per_facilitator_per_year",
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="base_costs",
            field=models.ManyToManyField(
                related_name="buildouts",
                through="programs.BuildoutBaseCostAssignment",
                to="programs.basecost",
            ),
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="responsibilities",
            field=models.ManyToManyField(
                related_name="buildouts",
                through="programs.BuildoutResponsibilityAssignment",
                to="programs.responsibility",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="responsibility",
            unique_together={("role", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="buildoutresponsibilityassignment",
            unique_together={("buildout", "responsibility")},
        ),
        migrations.AlterUniqueTogether(
            name="buildoutbasecostassignment",
            unique_together={("buildout", "base_cost")},
        ),
    ]
