# Generated by Django 4.2.23 on 2025-08-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0011_buildoutbasecostassignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programbuildout",
            name="new_workshop_concepts_per_year",
            field=models.PositiveIntegerField(
                default=1, help_text="New workshop concepts developed per year"
            ),
        ),
    ]
