# Generated by Django 4.2.23 on 2025-08-19 01:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0012_add_new_workshop_concepts_per_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="responsibility",
            name="hours",
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Published versions are immutable"
            ),
        ),
        migrations.AddField(
            model_name="responsibility",
            name="default_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Default hours per frequency unit",
                max_digits=6,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="default_frequency_unit",
            field=models.CharField(
                choices=[
                    ("PER_WORKSHOP_CONCEPT", "Per Workshop Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_WORKSHOP", "Per Workshop"),
                    ("PER_SESSION", "Per Session"),
                ],
                default="PER_WORKSHOP",
                help_text="Default frequency unit for this role",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="default_hours_per_frequency",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Default hours per frequency unit for this role",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="buildoutresponsibilityassignment",
            name="buildout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsibility_assignments_legacy",
                to="programs.programbuildout",
            ),
        ),
        migrations.AlterField(
            model_name="buildoutroleassignment",
            name="buildout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments_legacy",
                to="programs.programbuildout",
            ),
        ),
        migrations.CreateModel(
            name="BuildoutRoleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("PER_WORKSHOP", "Per Workshop"),
                            ("PER_SESSION", "Per Session"),
                            ("FLAT_RATE", "Flat Rate"),
                        ],
                        default="HOURLY",
                        help_text="How this contractor is paid for this role in this version",
                        max_length=32,
                    ),
                ),
                (
                    "pay_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Pay amount for this version",
                        max_digits=8,
                    ),
                ),
                (
                    "frequency_unit",
                    models.CharField(
                        choices=[
                            ("PER_WORKSHOP_CONCEPT", "Per Workshop Concept"),
                            ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                            ("PER_WORKSHOP", "Per Workshop"),
                            ("PER_SESSION", "Per Session"),
                        ],
                        help_text="Frequency unit for this role in this version",
                        max_length=32,
                    ),
                ),
                (
                    "frequency_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Multiplier for frequency calculations"
                    ),
                ),
                (
                    "hours_per_frequency",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hours per frequency unit for this version",
                        max_digits=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buildout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_lines",
                        to="programs.programbuildout",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        limit_choices_to={"groups__name__in": ["Contractor", "Admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildout_role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="programs.role"
                    ),
                ),
            ],
            options={
                "ordering": ["role__title"],
                "unique_together": {("buildout", "role")},
            },
        ),
        migrations.CreateModel(
            name="BuildoutResponsibilityLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hours per frequency unit for this version",
                        max_digits=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buildout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibility_lines",
                        to="programs.programbuildout",
                    ),
                ),
                (
                    "responsibility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programs.responsibility",
                    ),
                ),
            ],
            options={
                "ordering": ["responsibility__role__title", "responsibility__name"],
                "unique_together": {("buildout", "responsibility")},
            },
        ),
        migrations.AlterField(
            model_name="programbuildout",
            name="responsibilities",
            field=models.ManyToManyField(
                related_name="buildouts",
                through="programs.BuildoutResponsibilityLine",
                to="programs.responsibility",
            ),
        ),
        migrations.AlterField(
            model_name="programbuildout",
            name="roles",
            field=models.ManyToManyField(
                related_name="buildouts",
                through="programs.BuildoutRoleLine",
                to="programs.role",
            ),
        ),
        migrations.CreateModel(
            name="ContractorRoleRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("PER_WORKSHOP", "Per Workshop"),
                            ("PER_SESSION", "Per Session"),
                            ("FLAT_RATE", "Flat Rate"),
                        ],
                        default="HOURLY",
                        help_text="How this contractor is paid for this role",
                        max_length=32,
                    ),
                ),
                (
                    "pay_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pay amount (hourly rate, per workshop rate, etc.)",
                        max_digits=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        limit_choices_to={"groups__name__in": ["Contractor", "Admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_rates",
                        to="programs.role",
                    ),
                ),
            ],
            options={
                "ordering": ["contractor__email", "role__title"],
                "unique_together": {("contractor", "role")},
            },
        ),
    ]
