# Generated by Django 4.2.23 on 2025-08-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0014_migrate_legacy_data_to_new_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programbuildout",
            name="is_new_workshop",
        ),
        migrations.RemoveField(
            model_name="programbuildout",
            name="new_workshop_concepts_per_year",
        ),
        migrations.RemoveField(
            model_name="programbuildout",
            name="sessions_per_workshop",
        ),
        migrations.RemoveField(
            model_name="programbuildout",
            name="students_per_workshop",
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="is_new_program",
            field=models.BooleanField(
                default=False, help_text="Whether this is a new program concept"
            ),
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="new_program_concepts_per_year",
            field=models.PositiveIntegerField(
                default=1, help_text="New program concepts developed per year"
            ),
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="sessions_per_program",
            field=models.PositiveIntegerField(
                default=0, help_text="Sessions per program"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="students_per_program",
            field=models.PositiveIntegerField(
                default=0, help_text="Students per program"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="basecost",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                ],
                help_text="How often this cost occurs",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="buildoutroleline",
            name="frequency_unit",
            field=models.CharField(
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                ],
                help_text="Frequency unit for this role in this version",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="buildoutroleline",
            name="pay_type",
            field=models.CharField(
                choices=[
                    ("HOURLY", "Hourly"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("FLAT_RATE", "Flat Rate"),
                ],
                default="HOURLY",
                help_text="How this contractor is paid for this role in this version",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contractorrolerate",
            name="pay_type",
            field=models.CharField(
                choices=[
                    ("HOURLY", "Hourly"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("FLAT_RATE", "Flat Rate"),
                ],
                default="HOURLY",
                help_text="How this contractor is paid for this role",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contractorrolerate",
            name="pay_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Pay amount (hourly rate, per program rate, etc.)",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="programinstance",
            name="override_counts",
            field=models.JSONField(
                blank=True,
                help_text="JSON object with buildout count overrides (e.g., {'students_per_program': 8})",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="responsibility",
            name="frequency_type",
            field=models.CharField(
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                ],
                help_text="How often this responsibility occurs",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="default_frequency_unit",
            field=models.CharField(
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                ],
                default="PER_PROGRAM",
                help_text="Default frequency unit for this role",
                max_length=32,
            ),
        ),
    ]
