# Generated by Django 4.2.23 on 2025-08-19 20:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0015_rename_workshop_fields_to_program"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Duration in hours for each session of this program (e.g., 1.5 for 90 minutes)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.25"))
                        ],
                    ),
                ),
                (
                    "max_sessions",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of sessions of this program that can fit in this availability slot",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["program_buildout__title"],
            },
        ),
        migrations.CreateModel(
            name="ProgramSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(help_text="When this specific session starts"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(help_text="When this specific session ends"),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual duration of this session in hours",
                        max_digits=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "enrolled_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current number of children enrolled in this session",
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum children that can attend this session"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "availability_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="programs.availabilityprogram",
                    ),
                ),
                (
                    "program_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="programs.programinstance",
                    ),
                ),
            ],
            options={
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ProgramBuildoutScheduling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_session_duration",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        help_text="Default duration in hours for sessions of this program",
                        max_digits=4,
                    ),
                ),
                (
                    "min_session_duration",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.5"),
                        help_text="Minimum allowed session duration",
                        max_digits=4,
                    ),
                ),
                (
                    "max_session_duration",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("4.0"),
                        help_text="Maximum allowed session duration",
                        max_digits=4,
                    ),
                ),
                (
                    "max_students_per_session",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Maximum students allowed per individual session",
                    ),
                ),
                (
                    "requires_advance_booking",
                    models.BooleanField(
                        default=True,
                        help_text="Whether bookings must be made in advance",
                    ),
                ),
                (
                    "advance_booking_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Minimum hours in advance that bookings must be made",
                    ),
                ),
                (
                    "buildout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduling_config",
                        to="programs.programbuildout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Scheduling Configuration",
                "verbose_name_plural": "Program Scheduling Configurations",
            },
        ),
        migrations.CreateModel(
            name="ContractorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        help_text="When this availability period starts"
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        help_text="When this availability period ends"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("partially_booked", "Partially Booked"),
                            ("fully_booked", "Fully Booked"),
                            ("blocked", "Blocked/Unavailable"),
                        ],
                        default="available",
                        help_text="Current booking status of this time slot",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this availability (e.g., 'Prefer morning sessions')",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        limit_choices_to={"groups__name__in": ["Contractor", "Admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contractor Availability",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.AddField(
            model_name="availabilityprogram",
            name="availability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_offerings",
                to="programs.contractoravailability",
            ),
        ),
        migrations.AddField(
            model_name="availabilityprogram",
            name="program_buildout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_offerings",
                to="programs.programbuildout",
            ),
        ),
        migrations.CreateModel(
            name="SessionBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("waitlisted", "Waitlisted"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_notes",
                    models.TextField(
                        blank=True, help_text="Special notes or requests from parent"
                    ),
                ),
                (
                    "form_responses",
                    models.JSONField(
                        blank=True,
                        help_text="Responses to any required forms for this booking",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_bookings",
                        to="programs.child",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="programs.programsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-booked_at"],
                "unique_together": {("session", "child")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="availabilityprogram",
            unique_together={("availability", "program_buildout")},
        ),
    ]
