# Generated by Django 4.2.23 on 2025-08-21 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0016_availabilityprogram_programsession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractoravailability",
            name="exclude_holidays",
            field=models.BooleanField(
                default=False,
                help_text="If true, this availability will automatically exclude system holidays",
            ),
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the holiday (e.g., 'Christmas Day', 'Independence Day')",
                        max_length=100,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the holiday")),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this holiday recurs annually (e.g., Christmas vs. specific observed days)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about this holiday",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("name", "date")},
            },
        ),
        migrations.CreateModel(
            name="ContractorDayOffRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date requested for time off")),
                ("reason", models.TextField(help_text="Reason for time off request")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about the decision"
                    ),
                ),
                (
                    "affected_sessions_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of sessions that would be affected by this day off",
                    ),
                ),
                (
                    "affected_bookings_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of student bookings that would be affected",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        limit_choices_to={"groups__name__in": ["Contractor", "Admin"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_off_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "Admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_day_off_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("contractor", "date")},
            },
        ),
    ]
