# Generated by Django 4.2.23 on 2025-08-24 00:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0017_contractoravailability_exclude_holidays_holiday_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="buildoutroleline",
            unique_together={("buildout", "role", "contractor")},
        ),
    ]
