# Generated by Django 4.2.23 on 2025-08-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0018_allow_multiple_roles_per_contractor"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="visible_to_parents",
            field=models.BooleanField(
                default=True,
                help_text="Whether this role and assigned contractors are visible to parents in program listings and catalogs",
            ),
        ),
    ]
