# Generated by Django 4.2.23 on 2025-08-24 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0019_add_visible_to_parents_to_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("parent_request", "Parent Program Request"),
                            ("contractor_buildout", "Contractor Buildout Request"),
                        ],
                        max_length=32,
                    ),
                ),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "preferred_location",
                    models.CharField(
                        blank=True,
                        help_text="Preferred location for the program",
                        max_length=200,
                    ),
                ),
                (
                    "preferred_dates",
                    models.TextField(
                        blank=True, help_text="Preferred dates or time periods"
                    ),
                ),
                (
                    "expected_participants",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Expected number of participants",
                        null=True,
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional information or special requests",
                    ),
                ),
                (
                    "contractor_experience",
                    models.TextField(
                        blank=True,
                        help_text="Contractor's experience with this program type",
                    ),
                ),
                (
                    "proposed_location",
                    models.CharField(
                        blank=True,
                        help_text="Contractor's proposed location",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for administrators"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="programs.programtype",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_program_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
