# Generated by Django 4.2.23 on 2025-08-25 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("programs", "0020_add_program_request_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="programbuildout",
            name="assigned_contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buildouts",
                to="people.contractor",
            ),
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("ready", "Ready"),
                    ("awaiting_signatures", "Awaiting Signatures"),
                    ("active", "Active"),
                    ("on_hold", "On Hold"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="new",
                max_length=32,
            ),
        ),
    ]
