# Generated by Django 4.2.23 on 2025-08-25 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0021_programbuildout_assigned_contractor_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contractordayoffrequest",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="contractordayoffrequest",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="End date for time off request", null=True
            ),
        ),
        migrations.AddField(
            model_name="contractordayoffrequest",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Start date for time off request", null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractordayoffrequest",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Date requested for time off (legacy field)",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractordayoffrequest",
            unique_together={("contractor", "start_date", "end_date")},
        ),
    ]
