# Generated by Django 4.2.24 on 2025-09-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0024_add_role_assignment_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location name (e.g., Downtown Community Center)",
                        max_length=100,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Full address of the location"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details about the location"
                    ),
                ),
                (
                    "default_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default cost amount per frequency unit for this location",
                        max_digits=8,
                    ),
                ),
                (
                    "default_frequency",
                    models.CharField(
                        choices=[
                            ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                            ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                            ("PER_PROGRAM", "Per Program"),
                            ("PER_SESSION", "Per Session"),
                            ("PER_CHILD", "Per Child"),
                        ],
                        default="PER_PROGRAM",
                        help_text="Default frequency for location costs",
                        max_length=32,
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of participants this location can accommodate",
                        null=True,
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True,
                        help_text="Special features or amenities (e.g., projector, whiteboard, parking)",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, help_text="Primary contact person", max_length=100
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=20
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this location is available for booking",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="buildoutbasecostassignment",
            name="override_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("PER_CHILD", "Per Child"),
                ],
                help_text="Override frequency for this buildout (leave blank to use default)",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="buildoutbasecostassignment",
            name="override_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override rate for this buildout (leave blank to use default)",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="basecost",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("PER_CHILD", "Per Child"),
                ],
                help_text="How often this cost occurs",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="buildoutbasecostassignment",
            name="multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Multiplier for the final cost calculation",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="buildoutroleline",
            name="frequency_unit",
            field=models.CharField(
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("PER_CHILD", "Per Child"),
                ],
                help_text="Frequency unit for this role in this version",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="responsibility",
            name="frequency_type",
            field=models.CharField(
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("PER_CHILD", "Per Child"),
                ],
                help_text="How often this responsibility occurs",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="BuildoutLocationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override rate for this buildout (leave blank to use default)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "override_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                            ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                            ("PER_PROGRAM", "Per Program"),
                            ("PER_SESSION", "Per Session"),
                            ("PER_CHILD", "Per Child"),
                        ],
                        help_text="Override frequency for this buildout (leave blank to use default)",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for the final cost calculation",
                        max_digits=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buildout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_assignments",
                        to="programs.programbuildout",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programs.location",
                    ),
                ),
            ],
            options={
                "unique_together": {("buildout", "location")},
            },
        ),
        migrations.AddField(
            model_name="programbuildout",
            name="locations",
            field=models.ManyToManyField(
                related_name="buildouts",
                through="programs.BuildoutLocationAssignment",
                to="programs.location",
            ),
        ),
    ]
