# Generated by Django 4.2.24 on 2025-09-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0025_add_per_child_frequency_and_location_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildoutbasecostassignment",
            name="override_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("PER_CHILD", "Per Child"),
                ],
                help_text="Cost frequency (uses default if blank)",
                max_length=32,
                null=True,
                verbose_name="Frequency",
            ),
        ),
        migrations.AlterField(
            model_name="buildoutbasecostassignment",
            name="override_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost rate (uses default if blank)",
                max_digits=8,
                null=True,
                verbose_name="Rate",
            ),
        ),
        migrations.AlterField(
            model_name="buildoutlocationassignment",
            name="override_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("PER_CHILD", "Per Child"),
                ],
                help_text="Location frequency (uses default if blank)",
                max_length=32,
                null=True,
                verbose_name="Frequency",
            ),
        ),
        migrations.AlterField(
            model_name="buildoutlocationassignment",
            name="override_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Location rate (uses default if blank)",
                max_digits=8,
                null=True,
                verbose_name="Rate",
            ),
        ),
    ]
