# Generated by Django 4.2.24 on 2025-09-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0026_update_override_field_verbose_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildoutbasecostassignment",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("PER_CHILD", "Per Child"),
                ],
                help_text="Cost frequency for this buildout",
                max_length=32,
                null=True,
                verbose_name="Frequency",
            ),
        ),
        migrations.AddField(
            model_name="buildoutbasecostassignment",
            name="rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost rate for this buildout",
                max_digits=8,
                null=True,
                verbose_name="Rate",
            ),
        ),
        migrations.AddField(
            model_name="buildoutlocationassignment",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("PER_CHILD", "Per Child"),
                ],
                help_text="Location frequency for this buildout",
                max_length=32,
                null=True,
                verbose_name="Frequency",
            ),
        ),
        migrations.AddField(
            model_name="buildoutlocationassignment",
            name="rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Location rate for this buildout",
                max_digits=8,
                null=True,
                verbose_name="Rate",
            ),
        ),
        migrations.AlterField(
            model_name="buildoutbasecostassignment",
            name="override_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("PER_CHILD", "Per Child"),
                ],
                help_text="DEPRECATED: Use frequency field instead",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="buildoutbasecostassignment",
            name="override_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="DEPRECATED: Use rate field instead",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="buildoutlocationassignment",
            name="override_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PER_PROGRAM_CONCEPT", "Per Program Concept"),
                    ("PER_NEW_FACILITATOR", "Per New Facilitator"),
                    ("PER_PROGRAM", "Per Program"),
                    ("PER_SESSION", "Per Session"),
                    ("PER_CHILD", "Per Child"),
                ],
                help_text="DEPRECATED: Use frequency field instead",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="buildoutlocationassignment",
            name="override_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="DEPRECATED: Use rate field instead",
                max_digits=8,
                null=True,
            ),
        ),
    ]
