# Generated by Django 4.2.24 on 2025-10-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0028_populate_cost_location_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractoravailability",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Auto-set to False when end_datetime is in the past",
            ),
        ),
        migrations.AddField(
            model_name="contractoravailability",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Set to True when contractor archives this availability",
            ),
        ),
    ]
