# Generated by Django 4.2.24 on 2025-10-22 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0030_contractoravailability_legacy_availabilityrule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField(help_text="Date of the booking")),
                ("start_time", models.TimeField(help_text="Start time of the booking")),
                ("end_time", models.TimeField(help_text="End time of the booking")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Booking notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        help_text="Parent who made the booking",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        help_text="Child enrolled in this booking",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_bookings",
                        to="programs.child",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="The program being run during this booking",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_bookings",
                        to="programs.programinstance",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="The availability rule this booking falls under",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="programs.availabilityrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Booking",
                "verbose_name_plural": "Rule Bookings",
                "ordering": ["booking_date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["booking_date", "start_time"],
                        name="programs_ru_booking_3a9af4_idx",
                    ),
                    models.Index(
                        fields=["rule", "booking_date"],
                        name="programs_ru_rule_id_8f33d5_idx",
                    ),
                ],
            },
        ),
    ]
